version: "3"

services:
  nginx:
    build: nginx
    env_file: docker-env
    ports:
      - "80:80"
    volumes:
      - ~/www:/var/www/html
    tty: true

  php:
    build: php
    env_file: docker-env
    volumes:
      - "~/www:/var/www/html:rw,delegated"
    tty: true

  mysql:
    image: mariadb:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    env_file: docker-env
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true

  redis:
    image: redis:latest
    env_file: docker-env
    ports:
      - "6379:6379"
    tty: true

  maildev:
    image: djfarrelly/maildev
    env_file: docker-env
    depends_on:
      - php
    ports:
      - "1080:80"
